modLoader="javafml"
loaderVersion="[0,)"
license="All-Rights-Reserved"

[[mods]]
modId="hollowmine"
version="1.0-SNAPSHOT"
displayName="HollowMine"

authors="MAK"
description=""
[[dependencies.hollowmine]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.hollowmine]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"